# Homework 7


**Concepts covered:**

numpy arrays, array element access, basic descriptive statistics, initializing arrays, numpy functions and methods.  


**Instructions:**

Be sure to run each code block after you edit it to make sure it runs as expected. When you are done, we strongly recommend you run all the code from scratch (Runtime menu -> Restart and Run all) to make sure your current code works for all problems.

If your code raises an exception when run from scratch, it will interfere with the auto-grader process causing you to lose some or all points for this homework. Please ask for help on Piazza, attend office hours or schedule an appointment with your learning facilitator if you get stuck.


**Warning about AI:**

While we encourage you to use AI to generate practice problems, **we recommend against using generative AI in the strongest terms** to solve any part of this assignment. The goal of this assignment is for you to learn these concepts, and while using AI may help you obtain solutions to these problems, you will cheat yourself out of the learning that comes from working through the problems yourself.

**Sample Output:**

For each problem description, a sample output has been included to show what the expected output should be.


**Docstrings and Comments:**

Include a *documentation string* (docstring) for each function definition, as well as comments in the body of your code to explain each control structures (e.g., decision, loop), function call, or formula.

**Review Problem 1**

**Concept:** *List data type, list comprehension.*

**Task:**

Write a function `stdev(values)` that takes a 1D Python list of numbers and returns the population standard deviation.

**Sample Output:**


```
stdev([1, 2, 3]) should return approximately 0.8164965809

stdev([5, 5, 5, 5]) should return 0.0
```


In [224]:
# TO DO: WRITE YOUR SOLUTION HERE
import math

def stdev(values):
    '''take a 1D list of numbers and return the population std_dev'''
    #population std_dev is (sum of values - mean) ** 2 / n (# of elements)
    n = len(values)
    
    if n == 0:
        return 0 #can't divide by zero
   
    mean = sum(values) / n
    variance = sum((x - mean) ** 2 for x in values) / n
#variance is squared difference of value and population mean / # of values
    return math.sqrt(variance) #square root of variance is pop std_dev




In [225]:
# TO DO: WRITE YOUR TEST CASES HERE
print(stdev([3, 5, 9]))

2.494438257849294


**Review Problem 2**

**Concept:** *List element access.*

**Task:**

Write a function `sum_list(a, b)` that takes two same-length 1D lists and returns a new list containing the element-wise sums.

If the lengths differ, print a message indicating incompatible lengths in this format: Incompatible lengths: {len(a)} vs {len(b)}.
Use list comprehension for this, not numpy.

**Sample Output:**

```
sum_list([2, 4, 6], [1, 3, 5]) → [3, 7, 11]
```


In [226]:
# TO DO: WRITE YOUR SOLUTION HERE
def sum_list(a, b):
    '''take two 1D lists and return a new list containing element-wise sums'''
    
    if len(a) != len(b): #if length of a is not equal to length of b
        return(f"Incompatible lengths: {len(a)} vs {len(b)}") 
        

    return [a[i] + b[i] for i in range(len(a))]
    #across the range of the length of a, for index i return the index of
    #a plus the index of b





Test cases for problem 2

In [227]:
# TO DO: WRITE YOUR TEST CASES HERE
print(sum_list([2, 4, 6], [1, 3, 5]))
print(sum_list([1, 2, 3, 4, 5], [0, 1, 2, 3]))

[3, 7, 11]
Incompatible lengths: 5 vs 4


The following starter code will be used in several problems. Run the following cell before continuing.

In [228]:
# STARTER CODE TO DEFINE SOME NUMPY ARRAYS:
import numpy as np

a = np.arange(12)
b = np.array([i * 2 for i in range(1,13)])
c = np.random.randint(0, 10, 12)
print(f'a = {a}')
print(f'b = {b}')
print(f'c = {c}')



a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
b = [ 2  4  6  8 10 12 14 16 18 20 22 24]
c = [4 8 5 7 9 8 0 5 1 2 0 8]


**Problem 3**

**Concept:** *Array operations.*

**Task:**

Using the arrays a, b, c defined in the starter code:

a.   Compute sum of arrays `a` plus `b`, and store the result in the variable `x`.

b.   Compute the product of arrays `a` and `b`, and store the result in the variable `y`.

c.   Compute the dot product of arrays `a` and `b`, and store the result in the variable `z`.

d.   Re-shape the array `x` as a 2x6 array, and store the result in the variable `q`.

e.   Re-shape the array `y` as a 6x2 array, and store the result in the variable `r`.

f.   Compute the dot product of arrays `q` and `r`, and store the result in the varaible `s`.

Print `x`, `y`, `z`, `q`, `r`, `s` as you go to check your work.

**Sample Output:**

```
x = [ 3  7 11 15 19 23 27 31 35 39 43 47]
y = [  0   6  18  36  60  90 126 168 216 270 330 396]
z = 2184

q =
[[ 3  7 11 15 19 23]
 [27 31 35 39 43 47]]

r =
[[  0   6]
 [ 18  36]
 [ 60  90]
 [126 168]
 [216 270]
 [330 396]]

s =
[[15660 20484]
 [37476 49020]]

```


In [229]:
# TO DO: WRITE YOUR SOLUTION HERE
#sum of arrays a and b in x
x = a + b
print(f'x = {x}')
#product of arrays a and b in y
y = a * b
print(f'y = {y}')
#dot product of arrays a and b in z
z = np.dot(a, b) #dot product is sum of products of corresponding elements in a and b
print(f'z = {z}')
#reshape x as a 2x6 array and store in q
q = x.reshape(2, 6)
print(f'q = {q}')
#reshape y as a 6x2 array in r
r = y.reshape(6, 2)
print(f'r ={r}')
#dot product of q and r in s
s = np.dot(q, r)
print(f's = {s}')

x = [ 2  5  8 11 14 17 20 23 26 29 32 35]
y = [  0   4  12  24  40  60  84 112 144 180 220 264]
z = 1144
q = [[ 2  5  8 11 14 17]
 [20 23 26 29 32 35]]
r =[[  0   4]
 [ 12  24]
 [ 40  60]
 [ 84 112]
 [144 180]
 [220 264]]
s = [[ 7060  8848]
 [16060 20440]]


**Problem 4**

**Concept:** *Array operations, iteration with loop, numpy functions and methods.*

**Task:**

Write a function `mean_rowwise(x)` that takes a 2D numpy array and returns a 2D column vector containing the mean of each row.

**Numeric Example:**

If `x = [[1,2,3],[10,0,-10]]`, the row means are `[[2.],[0.]]`.


**Example Function Call:**

```
mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns [[0.3]]
```




In [230]:
# TO DO: WRITE YOUR SOLUTION HERE
def mean_rowwise(x):
    '''Take a 1D or 2D numpy array and return a 2D column vector containing
       the mean of each row.'''
    
    # If x is 1D, make it 2D with 1 row
    if x.ndim == 1: #if x is 1D, then reshape it to have 1 row and as many columns as needed
        x = x.reshape(1, -1) #-1 means "as many columns as needed"
    
    rows = x.shape[0] # number of rows
    means = [] #create an empty list to store the means of each row
    
    for i in range(rows): #for each row index in the range of the number of rows, loop
        row_mean = np.mean(x[i]) #calculate the mean of the row at index i
        means.append(row_mean) #append the mean of the row to the list of means
    
    # Convert list to column vector
    return np.array(means).reshape(rows, 1) 
#reshape the list of means to have as many rows as needed and 1 column, then return it as a numpy array


**Problem 4**

**Concept:** *Array operations, iteration with loop, numpy functions and methods.*

**Task:**

Write a function `mean_rowwise(x)` that takes a 2D numpy array and returns a 2D column vector containing the mean of each row.

**Numeric Example:**

If `x = [[1,2,3],[10,0,-10]]`, the row means are `[[2.],[0.]]`.


**Example Function Call:**

```
mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns [[0.3]]
```




Test cases for problem 4

In [231]:
# TO DO: WRITE YOUR TEST CASES HERE
mean_rowwise(np.array([0.2, 0.3, 0.4]))


array([[0.3]])

**Problem 5**

**Concept:** *Array operations, iteration with loop, boolean values, numpy functions and methods.*

**Task:**

Write a function `check_row_sum(x)` that returns `True` if every row in a 2D numpy array sums to 1.0 (tolerance: between `0.999` and `1.001`), otherwise return `False`.

**Example Function Calls:**

`check_row_sum([[0.2,0.8],[0.5,0.5]])` returns `True`

`check_row_sum([[0.0, 1.0], [0.9999, 0.0012]])` returns `False`
```



In [232]:
# TO DO: WRITE YOUR SOLUTION HERE
def check_row_sum(x):
    '''return true if every row of a 2d array sums to 1 (tolerance .999 to 1.001)
    otherwise return false'''
    x = np.array(x) #convert x to a numpy array

    if x.ndim == 1:
        x = x.reshape(-1, 1) #make sure x is 2d
        #if x is 1D, reshape it to 1 # of rows, -1 calculates # of columns automatically
        #as sort of a constant in any situation
        
    for i in range(x.shape[0]): #for each row index in the range of the number of rows in x, loop
        row_sum = np.sum(x[i]) #calculate the sum of the row at index i
        if not (.999 <= row_sum <= 1.001): #if the sum of the row is not between .999 and 1.001, return false
         return False
        
    return True #if all rows sum to 1, return true (within tolerance given)

Test cases for problem 5

In [233]:
# TO DO: WRITE YOUR TEST CASES HERE
print(check_row_sum([[0.2, 0.8], [0.5, 0.5]]))
print(check_row_sum([[0, 1.0], [0.9999, 0.0012]]))

True
False


**Problem 6**

**Concept:** *Array operations, numpy functions and methods.*

**Task:**

Write a function `softmax(z)` that takes in a 1D numpy array of values $z_i$, and returns an array composed of $\frac{e^{z_i}}{\sum e^{z_i}}$.

The output array shape should be the same as the input array shape.

This formula is the [softmax](https://en.wikipedia.org/wiki/Softmax_function) formula used to adjust raw machine learning outputs into more suitable probability estimates.

**Example Function Calls:**

`softmax(np.array([0,0]))` returns `np.array([0.5, 0.5])`

`softmax(np.array([-1, 0, 1]))` returns `np.array([0.09003057 0.24472847 0.66524096])`


In [234]:
# TO DO: WRITE YOUR SOLUTION HERE
def softmax(z):
    '''take a 1D numpy array of values z and return a list of probabilities'''
    # softmax is e^z_i / sum of e^z for all i
    # with softmax, inputs an be negative, zero, or positive
    # output is a list of probabilities that sum to 1
    # used to take raw data and understand as parts of the whole (like percentages)
    z = np.array(z, dtype=float) #convert z to a numpy array of floats
    #compute the exponentials of each element in z
    exp_z = np.exp(z)
    # divide by the sum of the exponentials to get probabilities
    softmax_z = exp_z / np.sum(exp_z)
    return softmax_z

Test cases for problem 6

In [235]:
# TO DO: WRITE YOUR TEST CASES HERE
print(softmax(np.array([0, 0])))
print(softmax(np.array([-1, 0, 1])))


[0.5 0.5]
[0.09003057 0.24472847 0.66524096]


**Problem 7**

**Concept:** *Array operations.*

**Task:**
Write `softmax_2d(z)` that applies softmax row-by-row to a 2D numpy array, returning an array of the same shape.

**Example Function Calls:**

`softmax_2d(np.array([[0,0],[1,1]]))` returns `np.array([[0.5,0.5],[0.5,0.5]])`


In [236]:
# TO DO: WRITE YOUR SOLUTION HERE
def softmax_2d(z):
    '''Apply softmax row-wise to a 2D numpy array.
    Returns an array of the same shape'''
    
    # Convert input to numpy array
    z = np.array(z, dtype=float)
    
    
    # find the exponent of each element in z
    exp_z = np.exp(z)
    
    # sum of exponentials for each row, keepdims=True to maintain 2D shape for broadcasting
    softmax_z = exp_z / np.sum(exp_z, axis=1, keepdims=True)
    
    return softmax_z


Test cases for problem 7

In [237]:
# TO DO: WRITE YOUR TEST CASES HERE
softmax_2d(np.array([[0, 0], [1, 1]]))



array([[0.5, 0.5],
       [0.5, 0.5]])

**Problem 8**

**Concept:** *Descriptive statistics, row-wise operations, numpy functions and methods.*

**Task:**

Write `three_stats(x)` that takes an `n x k` array and returns an 3 by N array of:

1. row minimums

2. row medians

3. row maximums


**Hint:**
You can use np.min, np.median, np.max

**Example Function Calls:**

`three_stats(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))`
returns
`np.array([[1. 4. 7.], [2. 5. 8.], [3. 6. 9.]])`



In [238]:
# TO DO: WRITE YOUR SOLUTION HERE
def three_stats(x):
    '''take an array n x k and return a 3 x n array of row minimums,
    row medians, and row maximums'''
    x = np.array(x, dtype=float) #convert x to a numpy array of floats
    #Compute row-wise minimums, medians, and maximums
    #axis= 1 means we want to compute the stats across the columns for each row
    row_mins = np.min(x, axis=1) #compute the minimum of each
    row_medians = np.median(x, axis=1) #compute the median of each row
    row_maxs = np.max(x, axis=1) #compute the maximum of each row

    #combine the row stats into a 3 x n array
    result = np.vstack((row_mins, row_medians, row_maxs))
    #vstack stacks the row stats vertically to create a 3 x n array
    return result

Test cases for problem 8

In [239]:
# TO DO: WRITE YOUR TEST CASES HERE
three_stats([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

**Problem 9**

**Concept:** *Row-wise operations, numpy functions and methods.*

**Task:**
Write `max_row_sum(a)` that takes a 2D numpy array and returns the largest row sum.

**Numeric Example:**

```[[1,2],[10,-1],[0,0]] row sums [3,9,0] → returns 9```

**Example Function Call:**

`max_row_sum(np.array([[1, 2, 3], [9, 9, 9], [1000, 100, 900]]))` returns `2000`




In [240]:
# TO DO: WRITE YOUR SOLUTION HERE
def max_row_sum(a):
    '''takes a 2D array and return the largest row sum'''
    #convert to a numpy array
    a = np.array(a, dtype=float)
    #compute the sum of each row
    row_sums = np.sum(a, axis=1) #sum across columns for each
    return np.max(row_sums) #return the maximum of the row sums

Test cases for problem 9

In [241]:
# TO DO: WRITE YOUR TEST CASES HERE
max_row_sum([[1, 2, 3], [9, 9, 9], [1000, 100, 900]])

np.float64(2000.0)

**Problem 10**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

Write the function `array_init_parameters(a)` that returns either:

*  if all elements are the same and the array `a` can be recreated using `np.full((w, h), v)`, return the tuple `(w, h, v)` corresponding to (width, height, value)

* otherwise return `None`

**Numeric Example:**

```[[7,7],[7,7]] → (2,2,7)```

```[[7,7],[7,8]] → None```



In [242]:
# TO DO: WRITE YOUR SOLUTION HERE
def array_init_parameters(a):
    '''if all elements are the same and the array a can be recreated using
    np.full(w, h, v), return the tuple (w, h, v) otherwise return None'''
    #convert to a numpy array
    a = np.array(a, dtype=float)
    #get the shape of the array
    rows, cols = a.shape #get the unique values in the array
    # get the value of the first element (since all elements are the same, 
    #we can just take the first element as the value to fill)
    v = a[0, 0] 
    #check if all elements are the same as v
    if np.all(a == v):
        return (rows, cols, v) #if all elements are the same, return the shape and value as a tuple
    else:
        return None #if not all elements are the same, return None

Test cases for problem 10

In [243]:
# TEST CASES TO TRY:

print(array_init_parameters(np.array([[0]])))

print(array_init_parameters(np.array([[0, 1]])))


print(array_init_parameters(np.array([[3], [3]])))

print(array_init_parameters(np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4]])))


(1, 1, np.float64(0.0))
None
(2, 1, np.float64(3.0))
(4, 3, np.float64(4.0))


**Problem 11**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

[Kakuro](https://en.wikipedia.org/wiki/Kakuro) is a logic puzzle where the goal is to fill in numbers so that the rows and columns add up to specified numbers.

Write `kakuro_test(a, row_sums, column_sums)` that returns `True` if:

* each row sum matches `row_sums`

* each column sum matches `column_sums`

* Otherwise return `False`.

**Numeric Example:**

For the input
`kakuro_test(np.array([[7, 2], [3, 4]]), [9, 7], [10, 6])`

The row sums are 7+2=9 and 3+4=7, which matches the third element `[9, 7]`

The column sums are 7+3=10 and 2+4=6, which matches the fourth element `[10, 6]`

So this should return `True`



In [244]:
# TO DO: WRITE YOUR SOLUTION HERE
def kakuro_test(a, row_sums, column_sums):
    '''returns true if row_sums matches each row sum, column_sums matches each column sum,
    otherwise returns false'''
    #convert to a numpoy array
    a = np.array(a, dtype=float)
    # compute row sums and column sums
    rows_comp = np.all(np.sum(a, axis=1) == row_sums) 
    # check if all row sums match the given row_sums
    cols_comp = np.all(np.sum(a, axis=0) == column_sums) #axis=0 means we want to compute 
    #the sums down the columns for each column

    #return true if both row sums and column sums match, otherwise return false
    return rows_comp and cols_comp

Test cases for problem 11

In [245]:
# TEST CASES TO TRYU

# this should return True
p11_test_1_result = kakuro_test(np.array([[0, 1, 2], [3, 4, 5]]), [3, 12], [3, 5, 7])
print(f'p11_test_1_result = {p11_test_1_result}')

# this should return False
p11_test_2_result = kakuro_test(np.array([[0, 2, 4], [3, 4, 5]]), [3, 12], [3, 5, 7])
print(f'p11_test_2_result = {p11_test_2_result}')



p11_test_1_result = True
p11_test_2_result = False


**Problem 12**

**Concept:** *File reading, parsing data values, array creation.*

**Task:**
Write the function `read_csv_to_array(filename)` that reads a CSV file, discards the header row, converts each element to a floating-point number, and returns a 2D numpy array.

**Sample Output:**

If file contains:

```
foo,bar
2,4
6,8
```

The function should return:
```
np.array([[2. 4.][6. 8.]])
```

In [246]:
# TO DO: WRITE YOUR SOLUTION HERE
import csv

def read_csv_to_array(filename):
    '''reads a csv, discards the header, converts each element to a float, and 
    returns a 2d numpy array'''
    data = [] #create an empty list to store the data from the csv
    with open(filename, 'r') as f: #open the file for reading
        reader = csv.reader(f) #create a csv reader object

        next(reader) #skip the header row
        
        for row in reader: #for each row in the csv reader object, loop
            #convert each element to a float and append the row to the data list
            data.append([float(x) for x in row])

            #convert the data list to a 2D numpy array and return it
        return np.array(data, dtype=float)

Test cases for problem 12

In [247]:
# TEST CASES HERE
data = read_csv_to_array("data1.csv")
print(data)


[[ 22. 183.  51.]
 [ 62. 168.  57.]
 [ 42. 150.  98.]
 [ 49. 163.  90.]
 [ 49. 129.  98.]
 [ 60. 171.  90.]
 [ 59. 181.  65.]
 [ 62. 136.  83.]
 [ 18. 144.  67.]
 [ 64. 189.  73.]]


**Problem 13**

**Concept:** *File reading, parsing data values, array creation.*


**Task:**

Write the function `get_column_stats(filename)` that a CSV file, discards the header row, and returns a 1D numpy array containing the mean of each column.

**Sample Output:**

If file contains:
```
a,b,c
1,2,3
4,5,6
```
The resulting columns means are

```np.array([2.5, 3.5, 4.5])```


In [248]:
# TO DO: WRITE YOUR SOLUTION HERE

def get_column_stats(filename):
    '''updateCSV file, discards the header row, and returns a 2D numpy array 
    where the rows contain in order: the means, standard deviations, minimums, 
    and maximums, of each column'''
    # load the data from the csv file skipping the header row
    data = np.loadtxt(filename, delimiter=',', skiprows=1)
    
    # compute the mean of each column axis 0 means operate down the rows for each column
    means = np.mean(data, axis=0)
    
    # compute the standard deviation of each column axis 0 means compute per column ddof 0 is population std not sample std
    stds = np.std(data, axis=0, ddof=0)
    
    # compute the minimum value of each column axis 0 means check each column separately
    mins = np.min(data, axis=0)
    
    # compute the maximum value of each column axis 0 means check each column separately
    maxs = np.max(data, axis=0)
    
    # combine all statistics into a single 2d array the first row will be means second std third min fourth max
    result = np.array([means, stds, mins, maxs])
    
    # return the resulting array
    return result

Test cases for problem 13

In [249]:
# TEST CASES HERE
stats = get_column_stats("data1.csv")
print(stats)


[[ 48.7        161.4         77.2       ]
 [ 15.88112087  19.6936538   16.09844713]
 [ 18.         129.          51.        ]
 [ 64.         189.          98.        ]]
